from raptus.browsermessage import browsermessageMessageFactory as _

BROWSERS = [
    ("isWebKit","WebKit"),
    ("isOpera","Opera"),
    ("isChrome","Chrome"),
    ("isSafari","Safari"),
    ("isSafari3","Safari 3"),
    ("isSafari4","Safari 4"),
    ("isIE","IE"),
    ("isIE7","IE 7"),
    ("isIE8","IE 8"),
    ("isIE6","IE 6"),
    ("isGecko","Gecko"),
    ("isGecko2","Gecko 2"),
    ("isGecko3","Gecko 3"),
    ("isFirefox","Firefox"),
    ("isFirefox1","Firefox 1"),
    ("isFirefox2","Firefox 2"),
    ("isFirefox3","Firefox 3"),
    ("isSafariOnMac",_(u"Safari on Mac")),
    ("isSafariOnWin",_(u"Safari on Win")),
    ("isGeckoOnMac",_(u"Gecko on Mac")),
    ("isGeckoOnLinux",_(u"Gecko on Linux")),
    ("isGeckoOnWin",_(u"Gecko on Win")),
    ("isFirefoxOnMac",_(u"Firefox on Mac")),
    ("isFirefoxOnLinux",_(u"Firefox on Linux")),
    ("isFirefoxOnWin",_(u"Firefox on Win")),
    ("isOperaOnMac",_(u"Opera on Mac")),
    ("isOperaOnLinux",_(u"Opera on Linux")),
    ("isOperaOnWin",_(u"Opera on Win")),
    ("isChromeOnMac",_(u"Chrome on Mac")),
    ("isChromeOnLinux",_(u"Chrome on Linux")),
    ("isChromeOnWin",_(u"Chrome on Win"))
]
